### ISSUE TITLE
Free balance

### ISSUE THREAD

**Issue by netdodger** [sammchardy/python-quoine#3]
I wish to retrieve the available (free) balance on my Qryptos account. If I use the  `get_account_balances()` function it returns  the total balance, which differs from free balance if one has an open order. I also tried using `get_crypto_accounts()`, however it does not contain the "free_margin" field unlike the `get_fiat_accounts()`. Thanks for your help in advance!

**Comment by sammchardy** [comment]
Hi @netdodger, it seems the `get_crypto_accounts` function doesn't return that. The relevant documentation is here on the Quoine API Reference https://developers.quoine.com/v2#get-crypto-accounts

Best thing may be to contact Quoine and ask them to update the output to show free balance.
